In [13]:
import numpy as np
import pandas as pd

np.random.seed(42)

In [14]:
vehicle_types=["Electric Van","Small Van", "Cargo Car" , "Medium Truck" , "Large Truck"]

In [15]:
vehicle_ids = [f"V{i:03d}" for i in range(1, 151)]

In [16]:
print(vehicle_ids[:10])
print(vehicle_ids[-5:])
print(len(vehicle_ids))

['V001', 'V002', 'V003', 'V004', 'V005', 'V006', 'V007', 'V008', 'V009', 'V010']
['V146', 'V147', 'V148', 'V149', 'V150']
150

In [21]:
vehicle_type_data=np.random.choice(vehicle_types,150,p=[0.15,0.2,0.4,0.15,0.1])

In [22]:
capacity_map = {
    "Electric Van": 300,
    "Small Van": 500,
    "Cargo Car": 800,
    "Medium Truck": 1200,
    "Large Truck": 2000
}

In [35]:
vehicles = pd.DataFrame({
    "vehicle_id": vehicle_ids,
    "vehicle_type": vehicle_type_data
})

In [34]:
vehicles["vehicle_type"].value_counts()

vehicle_type
Cargo Car       61
Small Van       29
Medium Truck    23
Electric Van    22
Large Truck     15
Name: count, dtype: int64

In [36]:
vehicles["max_load_kg"] = vehicles["vehicle_type"].map(capacity_map)

In [37]:
vehicles.head()

  vehicle_id  vehicle_type  max_load_kg
0       V001   Large Truck         2000
1       V002     Small Van          500
2       V003  Electric Van          300
3       V004     Cargo Car          800
4       V005   Large Truck         2000

In [38]:
fuel_map = {
    "Electric Van": "Electric",
    "Small Van": "Petrol",
    "Cargo Car": "Diesel",
    "Medium Truck": "Diesel",
    "Large Truck": "Petrol"
}

In [42]:
vehicles["fuel_type"]=vehicles["vehicle_type"].map(fuel_map)

In [43]:
vehicles.head()

  vehicle_id  vehicle_type  max_load_kg      FUEL fuel_type
0       V001   Large Truck         2000    Petrol    Petrol
1       V002     Small Van          500    Petrol    Petrol
2       V003  Electric Van          300  Electric  Electric
3       V004     Cargo Car          800    Diesel    Diesel
4       V005   Large Truck         2000    Petrol    Petrol

In [44]:
vehicles[["vehicle_type", "fuel_type"]].drop_duplicates()

   vehicle_type fuel_type
0   Large Truck    Petrol
1     Small Van    Petrol
2  Electric Van  Electric
3     Cargo Car    Diesel
7  Medium Truck    Diesel

In [45]:
age_ranges = {
    "Electric Van": (0, 5),
    "Small Van": (1, 8),
    "Cargo Car": (1, 10),
    "Medium Truck": (2, 12),
    "Large Truck": (2, 15)
}

In [46]:
ages = []
for vehicle_type in vehicles["vehicle_type"]:
    low, high = age_ranges[vehicle_type]
    age = np.random.randint(low, high + 1)
    ages.append(age)

In [47]:
vehicle_status = [
    "Active",
    "Maintenance",
    "Retired"
]

In [50]:
vehicle_status_data=np.random.choice(vehicle_status,150,p=[0.70,0.18,0.12])

In [54]:
vehicles["vehicle_status"]=vehicle_status_data

In [59]:
vehicles["vehicle_status"].value_counts()

vehicle_status
Active         119
Maintenance     18
Retired         13
Name: count, dtype: int64

In [64]:
maintenance_dates = pd.to_datetime(
    np.random.choice(
        pd.date_range(
            start="2025-01-01",
            end="2026-08-25"
        ),
        size=150
    )
)

In [65]:
maintenance_intervals = {
    "Electric Van": 12,
    "Small Van": 9,
    "Cargo Car": 8,
    "Medium Truck": 6,
    "Large Truck": 5
}

In [67]:
vehicles.columns

Index(['vehicle_id', 'vehicle_type', 'max_load_kg', 'FUEL', 'fuel_type',
       'vehicle_status'],
      dtype='str')

In [68]:
len(ages)

150

In [69]:
vehicles["vehicle_age_years"] = ages

In [70]:
vehicles.columns

Index(['vehicle_id', 'vehicle_type', 'max_load_kg', 'FUEL', 'fuel_type',
       'vehicle_status', 'vehicle_age_years'],
      dtype='str')

In [72]:
vehicles[
    ["vehicle_type", "vehicle_age_years", "last_maintenance_date"]
].head(10)

KeyError: "['last_maintenance_date'] not in index"

In [73]:
vehicles.columns

Index(['vehicle_id', 'vehicle_type', 'max_load_kg', 'FUEL', 'fuel_type',
       'vehicle_status', 'vehicle_age_years'],
      dtype='str')

In [74]:
maintenance_dates = []

for age in vehicles["vehicle_age_years"]:
    max_days = age * 365
    days_ago = np.random.randint(0, max_days + 1)
    maintenance_date = pd.Timestamp("2026-08-25") - pd.Timedelta(days=days_ago)
    maintenance_dates.append(maintenance_date)

In [75]:
len(maintenance_dates)

150

In [76]:
vehicles["last_maintenance_date"] = maintenance_dates

In [77]:
vehicles[
    ["vehicle_type", "vehicle_age_years", "last_maintenance_date"]
].head(10)

   vehicle_type  vehicle_age_years last_maintenance_date
0   Large Truck                 14            2024-09-20
1     Small Van                  8            2021-03-06
2  Electric Van                  3            2025-01-18
3     Cargo Car                  3            2025-07-23
4   Large Truck                  8            2018-10-22
5     Small Van                  8            2024-01-05
6     Cargo Car                  4            2023-06-19
7  Medium Truck                  3            2026-02-20
8     Small Van                  4            2026-06-26
9     Cargo Car                 10            2024-01-30

In [80]:
vehicles.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   vehicle_id             150 non-null    str
 1   vehicle_type           150 non-null    str
 2   max_load_kg            150 non-null    int64
 3   fuel_type              150 non-null    str
 4   vehicle_status         150 non-null    str
 5   vehicle_age_years      150 non-null    int64
 6   last_maintenance_date  150 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 12.3 KB

In [79]:
vehicles = vehicles.drop(columns=["FUEL"])

In [81]:
vehicles.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   vehicle_id             150 non-null    str
 1   vehicle_type           150 non-null    str
 2   max_load_kg            150 non-null    int64
 3   fuel_type              150 non-null    str
 4   vehicle_status         150 non-null    str
 5   vehicle_age_years      150 non-null    int64
 6   last_maintenance_date  150 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 12.3 KB

In [82]:
vehicles["vehicle_id"].duplicated().sum()

np.int64(0)

In [83]:
vehicles["vehicle_age_years"].describe()

count    150.00000
mean       5.76000
std        3.44015
min        0.00000
25%        3.00000
50%        5.00000
75%        8.00000
max       15.00000
Name: vehicle_age_years, dtype: float64

In [84]:
vehicles.to_csv("../data/raw/vehicles.csv", index=False)

In [85]:
vehicles

,vehicle_id,vehicle_type,max_load_kg,fuel_type,vehicle_status,vehicle_age_years,last_maintenance_date
0,V001,Large Truck,2000,Petrol,Active,14,2024-09-20
1,V002,Small Van,500,Petrol,Active,8,2021-03-06
2,V003,Electric Van,300,Electric,Maintenance,3,2025-01-18
3,V004,Cargo Car,800,Diesel,Active,3,2025-07-23
4,V005,Large Truck,2000,Petrol,Maintenance,8,2018-10-22
...,...,...,...,...,...,...,...
145,V146,Cargo Car,800,Diesel,Active,7,2022-01-08
146,V147,Medium Truck,1200,Diesel,Active,9,2023-07-16
147,V148,Small Van,500,Petrol,Active,7,2023-03-18
148,V149,Cargo Car,800,Diesel,Active,5,2026-08-09
149,V150,Electric Van,300,Electric,Active,3,2025-08-31

In [86]:
driver_ids = [f"D{i:03d}" for i in range(1, 181)]

In [87]:
experience_ranges = [
    (0,2),
    (3,5),
    (6,10),
    (11,20)
]

experience_probabilities = [0.30,0.35,0.25,0.10]

In [88]:
license_types = [
    "LMV",
    "Transport",
    "Heavy"
]
license_probabilities = [0.35, 0.45, 0.20]

In [94]:
license_data = np.random.choice(
    license_types,
    180,
    p=license_probabilities
)

In [95]:
pd.Series(license_data).value_counts()

Transport    82
LMV          66
Heavy        32
Name: count, dtype: int64

In [96]:
employment_types = [
    "Full-time",
    "Contract",
    "Part-time"
]
employment_probabilities = [0.70, 0.20, 0.10]

In [97]:
employment_data=np.random.choice(employment_types,180,p=employment_probabilities)

In [102]:
salary_ranges = {
    (0, 2): (22000, 28000),
    (3, 5): (28000, 36000),
    (6, 10): (36000, 48000),
    (11, 20): (48000, 65000)
}

In [103]:
driver_experience = []

for _ in range(180):
    experience_range = np.random.choice(
        len(experience_ranges),
        p=experience_probabilities
    )
    
    low, high = experience_ranges[experience_range]
    experience = np.random.randint(low, high + 1)
    driver_experience.append(experience)

In [104]:
len(driver_experience)

180

In [105]:
salaries = []

for experience in driver_experience:
    if experience <= 2:
        low, high = salary_ranges[(0, 2)]
    elif experience <= 5:
        low, high = salary_ranges[(3, 5)]
    elif experience <= 10:
        low, high = salary_ranges[(6, 10)]
    else:
        low, high = salary_ranges[(11, 20)]

    salary = np.random.randint(low, high + 1)
    salaries.append(salary)

In [106]:
len(salaries)

180

In [107]:
salaries[:10]

[27844, 25243, 25359, 36685, 30160, 60258, 34265, 45759, 27341, 22038]

In [108]:
shift_types = [
    "Morning",
    "Afternoon",
    "Night"
]

shift_probabilities = [0.40, 0.35, 0.25]

In [109]:
shift_data = np.random.choice(
    shift_types,
    180,
    p=shift_probabilities
)

In [110]:
pd.Series(shift_data).value_counts()

Morning      69
Afternoon    62
Night        49
Name: count, dtype: int64

In [111]:
driver_status = [
    "Active",
    "Leave",
    "Inactive"
]

driver_status_probabilities = [0.90, 0.07, 0.03]

In [112]:
driver_status_data = np.random.choice(
    driver_status,
    180,
    p=driver_status_probabilities
)

In [113]:
pd.Series(driver_status_data).value_counts()

Active      166
Leave         9
Inactive      5
Name: count, dtype: int64

In [114]:
drivers = pd.DataFrame({
    "driver_id": driver_ids,
    "driver_experience_years": driver_experience,
    "license_type": license_data,
    "employment_type": employment_data,
    "monthly_salary": salaries,
    "shift_type": shift_data,
    "driver_status": driver_status_data
})

In [115]:
drivers.head()

,driver_id,driver_experience_years,license_type,employment_type,monthly_salary,shift_type,driver_status
0,D001,1,LMV,Contract,27844,Night,Active
1,D002,2,Transport,Full-time,25243,Morning,Active
2,D003,1,Transport,Contract,25359,Afternoon,Active
3,D004,6,Transport,Part-time,36685,Night,Active
4,D005,4,LMV,Full-time,30160,Morning,Active

In [116]:
drivers.isnull().sum()

driver_id                  0
driver_experience_years    0
license_type               0
employment_type            0
monthly_salary             0
shift_type                 0
driver_status              0
dtype: int64

In [117]:
drivers["driver_id"].duplicated().sum()

np.int64(0)

In [118]:
drivers["monthly_salary"].describe()

count      180.000000
mean     34328.788889
std       9742.062290
min      22022.000000
25%      27144.750000
50%      32032.500000
75%      38526.750000
max      64184.000000
Name: monthly_salary, dtype: float64

In [119]:
drivers.to_csv("../data/raw/drivers.csv", index=False)

In [120]:
drivers

,driver_id,driver_experience_years,license_type,employment_type,monthly_salary,shift_type,driver_status
0,D001,1,LMV,Contract,27844,Night,Active
1,D002,2,Transport,Full-time,25243,Morning,Active
2,D003,1,Transport,Contract,25359,Afternoon,Active
3,D004,6,Transport,Part-time,36685,Night,Active
4,D005,4,LMV,Full-time,30160,Morning,Active
...,...,...,...,...,...,...,...
175,D176,1,Heavy,Contract,26256,Afternoon,Inactive
176,D177,0,LMV,Full-time,24448,Night,Active
177,D178,4,Heavy,Full-time,32293,Morning,Active
178,D179,3,Transport,Full-time,29283,Afternoon,Active
179,D180,1,Transport,Contract,22659,Morning,Active

In [121]:
customer_ids = [f"C{i:04d}" for i in range(1, 5001)]

In [122]:
customer_types = [
    "Individual",
    "Business",
    "Enterprise"
]

customer_type_probabilities = [0.70, 0.25, 0.05]

In [123]:
customer_type_data = np.random.choice(
    customer_types,
    5000,
    p=customer_type_probabilities
)

In [124]:
regions = [
    "Central",
    "North",
    "South",
    "East",
    "West"
]

region_probabilities = [0.25, 0.18, 0.20, 0.22, 0.15]

In [125]:
region_data = np.random.choice(
    regions,
    5000,
    p=region_probabilities
)

In [126]:
customers = pd.DataFrame({
    "customer_id": customer_ids,
    "customer_type": customer_type_data,
    "customer_region": region_data
})

In [127]:
customers["customer_type"].value_counts()

customer_type
Individual    3538
Business      1212
Enterprise     250
Name: count, dtype: int64

In [128]:
customers.isnull().sum()

customer_id        0
customer_type      0
customer_region    0
dtype: int64

In [129]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      5000 non-null   str
 1   customer_type    5000 non-null   str
 2   customer_region  5000 non-null   str
dtypes: str(3)
memory usage: 213.3 KB

In [130]:
customers.to_csv("../data/raw/customers.csv", index=False)

In [131]:
customers

     customer_id customer_type customer_region
0          C0001    Individual            West
1          C0002      Business         Central
2          C0003      Business           South
3          C0004    Individual           South
4          C0005    Individual            East
...          ...           ...             ...
4995       C4996    Individual            East
4996       C4997    Enterprise         Central
4997       C4998    Individual           North
4998       C4999    Individual         Central
4999       C5000    Individual         Central

[5000 rows x 3 columns]

In [132]:
route_ids = [f"R{i:03d}" for i in range(1, 101)]

In [133]:
locations = [
    "Central",
    "North",
    "South",
    "East",
    "West"
]

In [136]:
destinations = np.random.choice(locations, 100)

for i in range(100):
    while destinations[i] == origins[i]:
        destinations[i] = np.random.choice(locations)

In [137]:
(origins == destinations).sum()

np.int64(0)

In [138]:
distances = np.random.randint(3, 101, 100)

In [139]:
road_types = [
    "Urban",
    "Highway",
    "Mixed"
]

road_probabilities = [0.50, 0.25, 0.25]

In [140]:
road_type_data = np.random.choice(
    road_types,
    100,
    p=road_probabilities
)

In [141]:
road_conditions = [
    "Good",
    "Average",
    "Poor"
]

road_condition_probabilities = [0.60, 0.30, 0.10]

In [142]:
road_condition_data = np.random.choice(
    road_conditions,
    100,
    p=road_condition_probabilities
)

In [143]:
expected_travel_time = (distances / 40) * 60
expected_travel_time = expected_travel_time * np.random.uniform(
    0.9,
    1.2,
    100
)

In [144]:
routes = pd.DataFrame({
    "route_id": route_ids,
    "origin": origins,
    "destination": destinations,
    "distance_km": distances,
    "road_type": road_type_data,
    "road_condition": road_condition_data,
    "expected_travel_time_min": expected_travel_time.round(1)
})

In [145]:
routes.head()

,route_id,origin,destination,distance_km,road_type,road_condition,expected_travel_time_min
0,R001,North,Central,31,Urban,Average,50.6
1,R002,Central,South,74,Highway,Good,115.5
2,R003,West,North,53,Mixed,Good,76.7
3,R004,North,West,44,Urban,Good,66.0
4,R005,East,North,33,Highway,Average,58.8

In [146]:
routes.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   route_id                  100 non-null    str
 1   origin                    100 non-null    str
 2   destination               100 non-null    str
 3   distance_km               100 non-null    int32
 4   road_type                 100 non-null    str
 5   road_condition            100 non-null    str
 6   expected_travel_time_min  100 non-null    float64
dtypes: float64(1), int32(1), str(5)
memory usage: 7.6 KB

In [147]:
routes.isnull().sum()

route_id                    0
origin                      0
destination                 0
distance_km                 0
road_type                   0
road_condition              0
expected_travel_time_min    0
dtype: int64

In [148]:
routes.to_csv("../data/raw/routes.csv", index=False)

In [149]:
routes

,route_id,origin,destination,distance_km,road_type,road_condition,expected_travel_time_min
0,R001,North,Central,31,Urban,Average,50.6
1,R002,Central,South,74,Highway,Good,115.5
2,R003,West,North,53,Mixed,Good,76.7
3,R004,North,West,44,Urban,Good,66.0
4,R005,East,North,33,Highway,Average,58.8
...,...,...,...,...,...,...,...
95,R096,East,West,20,Urban,Average,32.5
96,R097,Central,South,37,Urban,Good,54.8
97,R098,West,South,14,Highway,Good,21.6
98,R099,North,South,53,Mixed,Good,88.4
99,R100,West,North,91,Urban,Average,162.7

In [150]:
print("Vehicles:", len(vehicles))
print("Drivers:", len(drivers))
print("Customers:", len(customers))
print("Routes:", len(routes))

Vehicles: 150
Drivers: 180
Customers: 5000
Routes: 100

In [151]:
print("Vehicles")
print(vehicles.isnull().sum())

print("\nDrivers")
print(drivers.isnull().sum())

print("\nCustomers")
print(customers.isnull().sum())

print("\nRoutes")
print(routes.isnull().sum())

Vehicles
vehicle_id               0
vehicle_type             0
max_load_kg              0
fuel_type                0
vehicle_status           0
vehicle_age_years        0
last_maintenance_date    0
dtype: int64

Drivers
driver_id                  0
driver_experience_years    0
license_type               0
employment_type            0
monthly_salary             0
shift_type                 0
driver_status              0
dtype: int64

Customers
customer_id        0
customer_type      0
customer_region    0
dtype: int64

Routes
route_id                    0
origin                      0
destination                 0
distance_km                 0
road_type                   0
road_condition              0
expected_travel_time_min    0
dtype: int64

In [152]:
print("Vehicle duplicates:", vehicles["vehicle_id"].duplicated().sum())
print("Driver duplicates:", drivers["driver_id"].duplicated().sum())
print("Customer duplicates:", customers["customer_id"].duplicated().sum())
print("Route duplicates:", routes["route_id"].duplicated().sum())

Vehicle duplicates: 0
Driver duplicates: 0
Customer duplicates: 0
Route duplicates: 0

In [153]:
vehicles.groupby("vehicle_type")["max_load_kg"].unique()

vehicle_type
Cargo Car        [800]
Electric Van     [300]
Large Truck     [2000]
Medium Truck    [1200]
Small Van        [500]
Name: max_load_kg, dtype: object

In [154]:
drivers.groupby("driver_experience_years")["monthly_salary"].mean().head(10)

driver_experience_years
0    25106.208333
1    25645.933333
2    24668.250000
3    31942.120000
4    31383.913043
5    32745.222222
6    41175.833333
7    40333.454545
8    44600.400000
9    42043.533333
Name: monthly_salary, dtype: float64

In [155]:
routes[["distance_km", "expected_travel_time_min"]].head(10)

   distance_km  expected_travel_time_min
0           31                      50.6
1           74                     115.5
2           53                      76.7
3           44                      66.0
4           33                      58.8
5           65                     103.0
6           28                      42.8
7           20                      31.7
8           84                     142.8
9           59                      88.7