In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

In [2]:
vehicle_types=["Electric Van","Small Van", "Cargo Car" , "Medium Truck" , "Large Truck"]

In [3]:
vehicle_ids = [f"V{i:03d}" for i in range(1, 151)]

In [4]:
print(vehicle_ids[:10])
print(vehicle_ids[-5:])
print(len(vehicle_ids))

['V001', 'V002', 'V003', 'V004', 'V005', 'V006', 'V007', 'V008', 'V009', 'V010']
['V146', 'V147', 'V148', 'V149', 'V150']
150

In [5]:
vehicle_type_data=np.random.choice(vehicle_types,150,p=[0.15,0.2,0.4,0.15,0.1])

In [6]:
capacity_map = {
    "Electric Van": 300,
    "Small Van": 500,
    "Cargo Car": 800,
    "Medium Truck": 1200,
    "Large Truck": 2000
}

In [7]:
vehicles = pd.DataFrame({
    "vehicle_id": vehicle_ids,
    "vehicle_type": vehicle_type_data
})

In [8]:
vehicles["vehicle_type"].value_counts()

vehicle_type
Cargo Car       49
Small Van       37
Electric Van    26
Medium Truck    24
Large Truck     14
Name: count, dtype: int64

In [9]:
vehicles["max_load_kg"] = vehicles["vehicle_type"].map(capacity_map)

In [10]:
vehicles.head()

  vehicle_id vehicle_type  max_load_kg
0       V001    Cargo Car          800
1       V002  Large Truck         2000
2       V003    Cargo Car          800
3       V004    Cargo Car          800
4       V005    Small Van          500

In [11]:
fuel_map = {
    "Electric Van": "Electric",
    "Small Van": "Petrol",
    "Cargo Car": "Diesel",
    "Medium Truck": "Diesel",
    "Large Truck": "Petrol"
}

In [12]:
vehicles["fuel_type"]=vehicles["vehicle_type"].map(fuel_map)

In [13]:
vehicles.head()

  vehicle_id vehicle_type  max_load_kg fuel_type
0       V001    Cargo Car          800    Diesel
1       V002  Large Truck         2000    Petrol
2       V003    Cargo Car          800    Diesel
3       V004    Cargo Car          800    Diesel
4       V005    Small Van          500    Petrol

In [14]:
vehicles[["vehicle_type", "fuel_type"]].drop_duplicates()

   vehicle_type fuel_type
0     Cargo Car    Diesel
1   Large Truck    Petrol
4     Small Van    Petrol
6  Electric Van  Electric
7  Medium Truck    Diesel

In [15]:
age_ranges = {
    "Electric Van": (0, 5),
    "Small Van": (1, 8),
    "Cargo Car": (1, 10),
    "Medium Truck": (2, 12),
    "Large Truck": (2, 15)
}

In [16]:
ages = []
for vehicle_type in vehicles["vehicle_type"]:
    low, high = age_ranges[vehicle_type]
    age = np.random.randint(low, high + 1)
    ages.append(age)

In [17]:
vehicle_status = [
    "Active",
    "Maintenance",
    "Retired"
]

In [18]:
vehicle_status_data=np.random.choice(vehicle_status,150,p=[0.70,0.18,0.12])

In [19]:
vehicles["vehicle_status"]=vehicle_status_data

In [20]:
vehicles["vehicle_status"].value_counts()

vehicle_status
Active         115
Maintenance     19
Retired         16
Name: count, dtype: int64

In [21]:
maintenance_dates = pd.to_datetime(
    np.random.choice(
        pd.date_range(
            start="2025-01-01",
            end="2026-08-25"
        ),
        size=150
    )
)

In [22]:
maintenance_intervals = {
    "Electric Van": 12,
    "Small Van": 9,
    "Cargo Car": 8,
    "Medium Truck": 6,
    "Large Truck": 5
}

In [23]:
vehicles.columns

Index(['vehicle_id', 'vehicle_type', 'max_load_kg', 'fuel_type',
       'vehicle_status'],
      dtype='str')

In [24]:
len(ages)

150

In [25]:
vehicles["vehicle_age_years"] = ages

In [26]:
vehicles.columns

Index(['vehicle_id', 'vehicle_type', 'max_load_kg', 'fuel_type',
       'vehicle_status', 'vehicle_age_years'],
      dtype='str')

In [27]:
vehicles.columns

Index(['vehicle_id', 'vehicle_type', 'max_load_kg', 'fuel_type',
       'vehicle_status', 'vehicle_age_years'],
      dtype='str')

In [28]:
maintenance_dates = []

for age in vehicles["vehicle_age_years"]:
    max_days = age * 365
    days_ago = np.random.randint(0, max_days + 1)
    maintenance_date = pd.Timestamp("2026-08-25") - pd.Timedelta(days=days_ago)
    maintenance_dates.append(maintenance_date)

In [29]:
len(maintenance_dates)

150

In [30]:
vehicles["last_maintenance_date"] = maintenance_dates

In [31]:
vehicles[
    ["vehicle_type", "vehicle_age_years", "last_maintenance_date"]
].head(10)

   vehicle_type  vehicle_age_years last_maintenance_date
0     Cargo Car                  1            2026-04-02
1   Large Truck                  2            2026-01-14
2     Cargo Car                  3            2026-03-02
3     Cargo Car                  2            2025-11-17
4     Small Van                  5            2026-06-24
5     Small Van                  4            2023-04-03
6  Electric Van                  1            2025-09-18
7  Medium Truck                  7            2024-10-06
8     Cargo Car                  7            2022-08-02
9     Cargo Car                  4            2026-05-13

In [32]:
vehicles[
    ["vehicle_type", "vehicle_age_years", "last_maintenance_date"]
].head(10)

   vehicle_type  vehicle_age_years last_maintenance_date
0     Cargo Car                  1            2026-04-02
1   Large Truck                  2            2026-01-14
2     Cargo Car                  3            2026-03-02
3     Cargo Car                  2            2025-11-17
4     Small Van                  5            2026-06-24
5     Small Van                  4            2023-04-03
6  Electric Van                  1            2025-09-18
7  Medium Truck                  7            2024-10-06
8     Cargo Car                  7            2022-08-02
9     Cargo Car                  4            2026-05-13

In [33]:
vehicles.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   vehicle_id             150 non-null    str
 1   vehicle_type           150 non-null    str
 2   max_load_kg            150 non-null    int64
 3   fuel_type              150 non-null    str
 4   vehicle_status         150 non-null    str
 5   vehicle_age_years      150 non-null    int64
 6   last_maintenance_date  150 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 12.3 KB

In [34]:
vehicles.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   vehicle_id             150 non-null    str
 1   vehicle_type           150 non-null    str
 2   max_load_kg            150 non-null    int64
 3   fuel_type              150 non-null    str
 4   vehicle_status         150 non-null    str
 5   vehicle_age_years      150 non-null    int64
 6   last_maintenance_date  150 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(2), str(4)
memory usage: 12.3 KB

In [35]:
vehicles["vehicle_id"].duplicated().sum()

np.int64(0)

In [36]:
vehicles["vehicle_age_years"].describe()

count    150.000000
mean       5.080000
std        3.259514
min        0.000000
25%        3.000000
50%        4.000000
75%        8.000000
max       15.000000
Name: vehicle_age_years, dtype: float64

In [37]:
vehicles.to_csv("../data/raw/vehicles.csv", index=False)

In [38]:
vehicles

,vehicle_id,vehicle_type,max_load_kg,fuel_type,vehicle_status,vehicle_age_years,last_maintenance_date
0,V001,Cargo Car,800,Diesel,Active,1,2026-04-02
1,V002,Large Truck,2000,Petrol,Active,2,2026-01-14
2,V003,Cargo Car,800,Diesel,Retired,3,2026-03-02
3,V004,Cargo Car,800,Diesel,Active,2,2025-11-17
4,V005,Small Van,500,Petrol,Active,5,2026-06-24
...,...,...,...,...,...,...,...
145,V146,Electric Van,300,Electric,Active,3,2024-12-09
146,V147,Cargo Car,800,Diesel,Active,9,2021-06-22
147,V148,Cargo Car,800,Diesel,Active,5,2023-02-26
148,V149,Electric Van,300,Electric,Maintenance,4,2024-09-06
149,V150,Small Van,500,Petrol,Active,1,2025-10-27

In [39]:
driver_ids = [f"D{i:03d}" for i in range(1, 181)]

In [40]:
experience_ranges = [
    (0,2),
    (3,5),
    (6,10),
    (11,20)
]

experience_probabilities = [0.30,0.35,0.25,0.10]

In [41]:
license_types = [
    "LMV",
    "Transport",
    "Heavy"
]
license_probabilities = [0.35, 0.45, 0.20]

In [42]:
license_data = np.random.choice(
    license_types,
    180,
    p=license_probabilities
)

In [43]:
pd.Series(license_data).value_counts()

Transport    83
LMV          66
Heavy        31
Name: count, dtype: int64

In [44]:
employment_types = [
    "Full-time",
    "Contract",
    "Part-time"
]
employment_probabilities = [0.70, 0.20, 0.10]

In [45]:
employment_data=np.random.choice(employment_types,180,p=employment_probabilities)

In [46]:
salary_ranges = {
    (0, 2): (22000, 28000),
    (3, 5): (28000, 36000),
    (6, 10): (36000, 48000),
    (11, 20): (48000, 65000)
}

In [47]:
driver_experience = []

for _ in range(180):
    experience_range = np.random.choice(
        len(experience_ranges),
        p=experience_probabilities
    )
    
    low, high = experience_ranges[experience_range]
    experience = np.random.randint(low, high + 1)
    driver_experience.append(experience)

In [48]:
len(driver_experience)

180

In [49]:
salaries = []

for experience in driver_experience:
    if experience <= 2:
        low, high = salary_ranges[(0, 2)]
    elif experience <= 5:
        low, high = salary_ranges[(3, 5)]
    elif experience <= 10:
        low, high = salary_ranges[(6, 10)]
    else:
        low, high = salary_ranges[(11, 20)]

    salary = np.random.randint(low, high + 1)
    salaries.append(salary)

In [50]:
len(salaries)

180

In [51]:
salaries[:10]

[22591, 33429, 33205, 34235, 24720, 22713, 22935, 26337, 22001, 54368]

In [52]:
shift_types = [
    "Morning",
    "Afternoon",
    "Night"
]

shift_probabilities = [0.40, 0.35, 0.25]

In [53]:
shift_data = np.random.choice(
    shift_types,
    180,
    p=shift_probabilities
)

In [54]:
pd.Series(shift_data).value_counts()

Afternoon    70
Morning      68
Night        42
Name: count, dtype: int64

In [55]:
driver_status = [
    "Active",
    "Leave",
    "Inactive"
]

driver_status_probabilities = [0.90, 0.07, 0.03]

In [56]:
driver_status_data = np.random.choice(
    driver_status,
    180,
    p=driver_status_probabilities
)

In [57]:
pd.Series(driver_status_data).value_counts()

Active      162
Inactive      9
Leave         9
Name: count, dtype: int64

In [58]:
drivers = pd.DataFrame({
    "driver_id": driver_ids,
    "driver_experience_years": driver_experience,
    "license_type": license_data,
    "employment_type": employment_data,
    "monthly_salary": salaries,
    "shift_type": shift_data,
    "driver_status": driver_status_data
})

In [59]:
drivers.head()

,driver_id,driver_experience_years,license_type,employment_type,monthly_salary,shift_type,driver_status
0,D001,0,Transport,Full-time,22591,Morning,Active
1,D002,3,Transport,Full-time,33429,Afternoon,Active
2,D003,5,Transport,Full-time,33205,Morning,Active
3,D004,3,Transport,Contract,34235,Night,Active
4,D005,2,Transport,Part-time,24720,Afternoon,Active

In [60]:
drivers.isnull().sum()

driver_id                  0
driver_experience_years    0
license_type               0
employment_type            0
monthly_salary             0
shift_type                 0
driver_status              0
dtype: int64

In [61]:
drivers["driver_id"].duplicated().sum()

np.int64(0)

In [62]:
drivers["monthly_salary"].describe()

count      180.000000
mean     34682.938889
std       9973.275600
min      22001.000000
25%      26647.000000
50%      32418.000000
75%      41676.750000
max      64385.000000
Name: monthly_salary, dtype: float64

In [63]:
drivers.to_csv("../data/raw/drivers.csv", index=False)

In [64]:
drivers

,driver_id,driver_experience_years,license_type,employment_type,monthly_salary,shift_type,driver_status
0,D001,0,Transport,Full-time,22591,Morning,Active
1,D002,3,Transport,Full-time,33429,Afternoon,Active
2,D003,5,Transport,Full-time,33205,Morning,Active
3,D004,3,Transport,Contract,34235,Night,Active
4,D005,2,Transport,Part-time,24720,Afternoon,Active
...,...,...,...,...,...,...,...
175,D176,19,Transport,Full-time,54430,Morning,Active
176,D177,1,Transport,Full-time,25466,Afternoon,Active
177,D178,6,Heavy,Full-time,39081,Afternoon,Active
178,D179,0,Transport,Full-time,25778,Afternoon,Active
179,D180,5,LMV,Contract,28629,Morning,Active

In [65]:
customer_ids = [f"C{i:04d}" for i in range(1, 5001)]

In [66]:
customer_types = [
    "Individual",
    "Business",
    "Enterprise"
]

customer_type_probabilities = [0.70, 0.25, 0.05]

In [67]:
customer_type_data = np.random.choice(
    customer_types,
    5000,
    p=customer_type_probabilities
)

In [68]:
regions = [
    "Central",
    "North",
    "South",
    "East",
    "West"
]

region_probabilities = [0.25, 0.18, 0.20, 0.22, 0.15]

In [69]:
region_data = np.random.choice(
    regions,
    5000,
    p=region_probabilities
)

In [70]:
customers = pd.DataFrame({
    "customer_id": customer_ids,
    "customer_type": customer_type_data,
    "customer_region": region_data
})

In [71]:
customers["customer_type"].value_counts()

customer_type
Individual    3530
Business      1214
Enterprise     256
Name: count, dtype: int64

In [72]:
customers.isnull().sum()

customer_id        0
customer_type      0
customer_region    0
dtype: int64

In [73]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      5000 non-null   str
 1   customer_type    5000 non-null   str
 2   customer_region  5000 non-null   str
dtypes: str(3)
memory usage: 213.3 KB

In [74]:
customers.to_csv("../data/raw/customers.csv", index=False)

In [75]:
customers

     customer_id customer_type customer_region
0          C0001    Individual           North
1          C0002    Individual         Central
2          C0003    Enterprise         Central
3          C0004      Business           South
4          C0005    Enterprise            East
...          ...           ...             ...
4995       C4996    Individual         Central
4996       C4997    Enterprise         Central
4997       C4998    Individual         Central
4998       C4999    Individual           South
4999       C5000    Individual            West

[5000 rows x 3 columns]

In [76]:
route_ids = [f"R{i:03d}" for i in range(1, 101)]

In [77]:
locations = [
    "Central",
    "North",
    "South",
    "East",
    "West"
]
origins = np.random.choice(locations, 100)
destinations = np.random.choice(locations, 100)

In [78]:
destinations = np.random.choice(locations, 100)

for i in range(100):
    while destinations[i] == origins[i]:
        destinations[i] = np.random.choice(locations)

In [79]:
(origins == destinations).sum()

np.int64(0)

In [80]:
distances = np.random.randint(3, 101, 100)

In [81]:
road_types = [
    "Urban",
    "Highway",
    "Mixed"
]

road_probabilities = [0.50, 0.25, 0.25]

In [82]:
road_type_data = np.random.choice(
    road_types,
    100,
    p=road_probabilities
)

In [83]:
road_conditions = [
    "Good",
    "Average",
    "Poor"
]

road_condition_probabilities = [0.60, 0.30, 0.10]

In [84]:
road_condition_data = np.random.choice(
    road_conditions,
    100,
    p=road_condition_probabilities
)

In [85]:
expected_travel_time = (distances / 40) * 60
expected_travel_time = expected_travel_time * np.random.uniform(
    0.9,
    1.2,
    100
)

In [86]:
routes = pd.DataFrame({
    "route_id": route_ids,
    "origin": origins,
    "destination": destinations,
    "distance_km": distances,
    "road_type": road_type_data,
    "road_condition": road_condition_data,
    "expected_travel_time_min": expected_travel_time.round(1)
})

In [87]:
routes.head()

,route_id,origin,destination,distance_km,road_type,road_condition,expected_travel_time_min
0,R001,East,West,11,Highway,Average,19.7
1,R002,West,East,25,Urban,Good,36.2
2,R003,Central,North,47,Urban,Good,72.3
3,R004,Central,West,4,Urban,Good,5.9
4,R005,Central,West,16,Urban,Average,27.1

In [88]:
routes.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   route_id                  100 non-null    str
 1   origin                    100 non-null    str
 2   destination               100 non-null    str
 3   distance_km               100 non-null    int32
 4   road_type                 100 non-null    str
 5   road_condition            100 non-null    str
 6   expected_travel_time_min  100 non-null    float64
dtypes: float64(1), int32(1), str(5)
memory usage: 7.6 KB

In [89]:
routes.isnull().sum()

route_id                    0
origin                      0
destination                 0
distance_km                 0
road_type                   0
road_condition              0
expected_travel_time_min    0
dtype: int64

In [90]:
routes.to_csv("../data/raw/routes.csv", index=False)

In [91]:
routes

,route_id,origin,destination,distance_km,road_type,road_condition,expected_travel_time_min
0,R001,East,West,11,Highway,Average,19.7
1,R002,West,East,25,Urban,Good,36.2
2,R003,Central,North,47,Urban,Good,72.3
3,R004,Central,West,4,Urban,Good,5.9
4,R005,Central,West,16,Urban,Average,27.1
...,...,...,...,...,...,...,...
95,R096,North,West,75,Urban,Average,103.4
96,R097,North,Central,79,Highway,Average,132.1
97,R098,North,Central,42,Urban,Average,66.7
98,R099,West,East,56,Urban,Good,98.3
99,R100,Central,East,83,Urban,Good,123.7

In [92]:
print("Vehicles:", len(vehicles))
print("Drivers:", len(drivers))
print("Customers:", len(customers))
print("Routes:", len(routes))

Vehicles: 150
Drivers: 180
Customers: 5000
Routes: 100

In [93]:
print("Vehicles")
print(vehicles.isnull().sum())

print("\nDrivers")
print(drivers.isnull().sum())

print("\nCustomers")
print(customers.isnull().sum())

print("\nRoutes")
print(routes.isnull().sum())

Vehicles
vehicle_id               0
vehicle_type             0
max_load_kg              0
fuel_type                0
vehicle_status           0
vehicle_age_years        0
last_maintenance_date    0
dtype: int64

Drivers
driver_id                  0
driver_experience_years    0
license_type               0
employment_type            0
monthly_salary             0
shift_type                 0
driver_status              0
dtype: int64

Customers
customer_id        0
customer_type      0
customer_region    0
dtype: int64

Routes
route_id                    0
origin                      0
destination                 0
distance_km                 0
road_type                   0
road_condition              0
expected_travel_time_min    0
dtype: int64

In [94]:
print("Vehicle duplicates:", vehicles["vehicle_id"].duplicated().sum())
print("Driver duplicates:", drivers["driver_id"].duplicated().sum())
print("Customer duplicates:", customers["customer_id"].duplicated().sum())
print("Route duplicates:", routes["route_id"].duplicated().sum())

Vehicle duplicates: 0
Driver duplicates: 0
Customer duplicates: 0
Route duplicates: 0

In [95]:
vehicles.groupby("vehicle_type")["max_load_kg"].unique()

vehicle_type
Cargo Car        [800]
Electric Van     [300]
Large Truck     [2000]
Medium Truck    [1200]
Small Van        [500]
Name: max_load_kg, dtype: object

In [96]:
drivers.groupby("driver_experience_years")["monthly_salary"].mean().head(10)

driver_experience_years
0    24602.875000
1    24719.428571
2    24573.000000
3    31887.208333
4    31048.105263
5    32353.150000
6    42429.500000
7    42372.100000
8    42677.333333
9    40708.000000
Name: monthly_salary, dtype: float64

In [97]:
routes[["distance_km", "expected_travel_time_min"]].head(10)

   distance_km  expected_travel_time_min
0           11                      19.7
1           25                      36.2
2           47                      72.3
3            4                       5.9
4           16                      27.1
5           40                      67.8
6           42                      62.2
7           65                      90.1
8           84                     113.8
9           18                      27.8

In [98]:
dates = pd.date_range(
    start="2025-09-01",
    end="2026-08-25",
    freq="D"
)

In [99]:
dates[:5]

DatetimeIndex(['2025-09-01', '2025-09-02', '2025-09-03', '2025-09-04',
               '2025-09-05'],
              dtype='datetime64[us]', freq='D')

In [100]:
days_of_week = dates.dayofweek

In [101]:
days_of_week[:10]

Index([0, 1, 2, 3, 4, 5, 6, 0, 1, 2], dtype='int32')

In [102]:
demand_weights = np.array([
    1.0,  # Monday
    1.0,  # Tuesday
    1.0,  # Wednesday
    1.1,  # Thursday
    1.3,  # Friday
    0.8,  # Saturday
    0.6   # Sunday
])

In [103]:
daily_demand_weights = demand_weights[days_of_week]

In [104]:
daily_demand_weights[:10]

array([1. , 1. , 1. , 1.1, 1.3, 0.8, 0.6, 1. , 1. , 1. ])

In [105]:
demand_check = pd.DataFrame({
    "date": dates,
    "day": dates.day_name(),
    "weight": daily_demand_weights
})

In [106]:
demand_check

          date        day  weight
0   2025-09-01     Monday     1.0
1   2025-09-02    Tuesday     1.0
2   2025-09-03  Wednesday     1.0
3   2025-09-04   Thursday     1.1
4   2025-09-05     Friday     1.3
..         ...        ...     ...
354 2026-08-21     Friday     1.3
355 2026-08-22   Saturday     0.8
356 2026-08-23     Sunday     0.6
357 2026-08-24     Monday     1.0
358 2026-08-25    Tuesday     1.0

[359 rows x 3 columns]

In [107]:
daily_probabilities = (
    daily_demand_weights / daily_demand_weights.sum()
)

In [108]:
daily_probabilities[:7]

array([0.00286697, 0.00286697, 0.00286697, 0.00315367, 0.00372706,
       0.00229358, 0.00172018])

In [109]:
num_orders = 100000

In [110]:
order_dates=np.random.choice(dates,num_orders,p=daily_probabilities)

In [111]:
order_dates

array(['2026-03-26T00:00:00.000000', '2026-02-27T00:00:00.000000',
       '2026-02-23T00:00:00.000000', ..., '2026-03-07T00:00:00.000000',
       '2026-06-27T00:00:00.000000', '2026-04-23T00:00:00.000000'],
      shape=(100000,), dtype='datetime64[us]')

In [112]:
pd.Series(order_dates).value_counts().head(10)

2025-10-24    433
2025-10-31    416
2025-12-26    413
2026-07-10    404
2025-12-12    399
2025-09-26    394
2026-05-08    393
2026-03-13    393
2026-06-05    392
2026-07-03    391
Name: count, dtype: int64

In [113]:
package_types=["Small" , "Medium" , "Large" , "Fragile"]

In [114]:
package_probabilities=[0.4,0.35,0.15,0.1]

In [115]:
package_data=np.random.choice(package_types,num_orders,p=package_probabilities)

In [116]:
package_weight_ranges = {
    "Small": (1, 10),
    "Medium": (11, 30),
    "Large": (31, 100),
    "Fragile": (1, 20)
}

In [117]:
package_weights = []
for package_type in package_data:
    low, high = package_weight_ranges[package_type]
    weight = np.random.randint(low, high + 1)
    package_weights.append(weight)

In [118]:
order_customer_ids = np.random.choice(
    customers["customer_id"],
    num_orders
)

In [119]:
pd.Series(order_customer_ids).value_counts().head()

C3445    40
C1423    38
C2228    37
C3451    37
C1593    35
Name: count, dtype: int64

In [120]:
order_route_ids=np.random.choice(routes["route_id"],num_orders)

In [121]:
vehicle_groups = {}

for capacity in vehicles["max_load_kg"].unique():
    vehicle_groups[capacity] = vehicles[
        vehicles["max_load_kg"] == capacity
    ]["vehicle_id"].tolist()

In [122]:
order_vehicle_ids = []

capacities = sorted(vehicle_groups.keys())

for weight in package_weights:
    for capacity in capacities:
        if capacity >= weight:
            vehicle_id = np.random.choice(vehicle_groups[capacity])
            order_vehicle_ids.append(vehicle_id)
            break

In [123]:
vehicle_license_map = {
    "Electric Van": "LMV",
    "Small Van": "LMV",
    "Cargo Car": "Transport",
    "Medium Truck": "Heavy",
    "Large Truck": "Heavy"
}

In [124]:
vehicle_type_map = vehicles.set_index("vehicle_id")["vehicle_type"]

In [125]:
order_driver_ids = []

for vehicle_id in order_vehicle_ids:
    vehicle_type = vehicle_type_map[vehicle_id]
    required_license = vehicle_license_map[vehicle_type]

    eligible_drivers = drivers[
        drivers["license_type"] == required_license
    ]

    eligible_ids = eligible_drivers["driver_id"]
    driver_id = np.random.choice(eligible_ids)

    order_driver_ids.append(driver_id)

In [126]:
time_slots = [
    "Morning",
    "Late Morning",
    "Afternoon",
    "Evening",
    "Night"
]
time_probabilities = [0.20, 0.25, 0.30, 0.20, 0.05]

In [127]:
order_time_slots = np.random.choice(time_slots,num_orders,p=time_probabilities)

In [128]:
pd.Series(order_time_slots).value_counts()

Afternoon       29907
Late Morning    25136
Evening         19969
Morning         19893
Night            5095
Name: count, dtype: int64

In [129]:
route_time_map = routes.set_index("route_id")["expected_travel_time_min"]

In [130]:
order_expected_time = route_time_map[
    pd.Series(order_route_ids)
].to_numpy()

In [131]:
delay_multiplier = np.random.uniform(
    0.9,
    1.3,
    num_orders
)

In [132]:
actual_delivery_time = (
    order_expected_time * delay_multiplier
)

In [133]:
actual_delivery_time = actual_delivery_time.round(1)

In [134]:
delivery_delay = actual_delivery_time - order_expected_time

In [135]:
pd.Series(delivery_delay).describe()

count    100000.000000
mean          7.800919
std          11.338418
min         -16.000000
25%           0.000000
50%           4.700000
75%          14.200000
max          48.200000
dtype: float64

In [136]:
(delivery_delay > 0).mean()

np.float64(0.74749)

In [137]:
delivery_delay.mean()

np.float64(7.8009189999999995)

In [138]:
efficiency_map = {
    "Electric Van": 0.15,
    "Small Van": 0.10,
    "Cargo Car": 0.12,
    "Medium Truck": 0.25,
    "Large Truck": 0.35
}

In [139]:
order_vehicle_types = vehicle_type_map[
    pd.Series(order_vehicle_ids)
].to_numpy()

In [140]:
base_efficiency = pd.Series(order_vehicle_types).map(
    efficiency_map
).to_numpy()

In [141]:
route_distance_map = routes.set_index("route_id")["distance_km"]

In [142]:
order_distances = route_distance_map[
    pd.Series(order_route_ids)
].to_numpy()

In [143]:
fuel_consumption = base_efficiency * order_distances

In [144]:
vehicle_age_map = vehicles.set_index("vehicle_id")["vehicle_age_years"]

In [145]:
order_vehicle_age = vehicle_age_map[
    pd.Series(order_vehicle_ids)
].to_numpy()

In [146]:
age_factor = 1 + (order_vehicle_age * 0.015)

In [147]:
load_factor = 1 + (np.array(package_weights) / 1000)

In [148]:
fuel_consumption = (
    base_efficiency
    * order_distances
    * age_factor
    * load_factor
)

In [149]:
pd.Series(fuel_consumption).describe()

count    100000.000000
mean          7.864360
std           4.540055
min           0.450450
25%           4.254263
50%           7.359156
75%          11.845370
max          17.464343
dtype: float64

In [150]:
pd.DataFrame({
    "weight": package_weights,
    "fuel": fuel_consumption
}).corr()

          weight      fuel
weight  1.000000  0.033112
fuel    0.033112  1.000000

In [151]:
fuel_price_map = {
    "Petrol": 105,
    "Diesel": 95,
    "Electric": 10
}

In [152]:
vehicle_fuel_map = vehicles.set_index("vehicle_id")["fuel_type"]

In [153]:
order_fuel_types = vehicle_fuel_map[
    pd.Series(order_vehicle_ids)
].to_numpy()

In [154]:
fuel_prices = pd.Series(order_fuel_types).map(
    fuel_price_map
).to_numpy()

In [155]:
fuel_cost = fuel_consumption * fuel_prices

In [156]:
pd.Series(fuel_cost).describe()

count    100000.000000
mean         78.643602
std          45.400550
min           4.504500
25%          42.542625
50%          73.591560
75%         118.453695
max         174.643425
dtype: float64

In [157]:
fuel_cost[:10]

array([157.53402  ,  92.027925 , 157.6638   ,  47.0898375,  88.6578   ,
         6.41421  , 119.29872  ,  21.67326  , 108.806445 ,  67.7025   ])

In [158]:
driver_salary_map = drivers.set_index("driver_id")["monthly_salary"]

In [159]:
order_driver_salary = driver_salary_map[
    pd.Series(order_driver_ids)
].to_numpy()

In [160]:
driver_hourly_cost = order_driver_salary / 176

In [161]:
delivery_hours = actual_delivery_time / 60

In [162]:
driver_cost = driver_hourly_cost * delivery_hours

In [163]:
pd.Series(driver_cost).describe()

count    100000.000000
mean        289.021402
std         196.686253
min           8.582434
25%         137.947526
50%         260.046023
75%         403.261709
max        1232.461023
dtype: float64

In [164]:
operating_cost = fuel_cost + driver_cost

In [165]:
cost_per_order = operating_cost

In [166]:
pd.Series(cost_per_order).describe()

count    100000.000000
mean        367.665004
std         236.119769
min          13.374281
25%         181.924886
50%         338.856763
75%         523.463848
max        1388.089023
dtype: float64

In [167]:
cost_per_order[:10]

array([1199.58057303,  564.34894773,  516.70712386,  190.53407992,
        500.71620909,   20.03898273,  487.15383364,  135.13026758,
        472.08205106,  391.35890152])

In [168]:
pd.DataFrame({
    "distance": order_distances,
    "cost": cost_per_order
}).corr()

          distance      cost
distance  1.000000  0.893331
cost      0.893331  1.000000

In [169]:
pd.DataFrame({
    "weight": package_weights,
    "cost": cost_per_order
}).corr()

          weight      cost
weight  1.000000  0.002677
cost    0.002677  1.000000

In [170]:
order_ids = [f"O{i:06d}" for i in range(1, num_orders + 1)]

In [171]:
orders = pd.DataFrame({
    "order_id": order_ids,
    "customer_id": order_customer_ids,
    "vehicle_id": order_vehicle_ids,
    "driver_id": order_driver_ids,
    "route_id": order_route_ids,
    "order_date": order_dates,
    "time_slot": order_time_slots,
    "package_type": package_data,
    "package_weight_kg": package_weights,
    "expected_travel_time_min": order_expected_time,
    "actual_delivery_time_min": actual_delivery_time,
    "delivery_delay_min": delivery_delay,
    "fuel_consumption": fuel_consumption,
    "fuel_cost": fuel_cost,
    "driver_cost": driver_cost,
    "operating_cost": operating_cost,
    "cost_per_order": cost_per_order
})

In [172]:
orders.shape

(100000, 17)

In [173]:
orders.head()

,order_id,customer_id,vehicle_id,driver_id,route_id,order_date,time_slot,package_type,package_weight_kg,expected_travel_time_min,actual_delivery_time_min,delivery_delay_min,fuel_consumption,fuel_cost,driver_cost,operating_cost,cost_per_order
0,O000001,C4572,V149,D149,R035,2026-03-26,Morning,Fragile,11,141.8,182.8,41.0,15.753402,157.534020,1042.046553,1199.580573,1199.580573
1,O000002,C1060,V030,D072,R062,2026-02-27,Late Morning,Medium,30,85.7,94.5,8.8,9.202792,92.027925,472.321023,564.348948,564.348948
2,O000003,C3458,V073,D029,R018,2026-02-23,Evening,Small,8,135.1,126.7,-8.4,15.766380,157.663800,359.043324,516.707124,516.707124
3,O000004,C3935,V073,D139,R031,2026-02-11,Morning,Small,7,48.0,60.8,12.8,4.708984,47.089837,143.444242,190.534080,190.534080
4,O000005,C2984,V099,D055,R099,2025-11-13,Morning,Small,10,98.3,120.8,22.5,8.865780,88.657800,412.058409,500.716209,500.716209

In [174]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 17 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  100000 non-null  str
 1   customer_id               100000 non-null  str
 2   vehicle_id                100000 non-null  str
 3   driver_id                 100000 non-null  str
 4   route_id                  100000 non-null  str
 5   order_date                100000 non-null  datetime64[us]
 6   time_slot                 100000 non-null  str
 7   package_type              100000 non-null  str
 8   package_weight_kg         100000 non-null  int64
 9   expected_travel_time_min  100000 non-null  float64
 10  actual_delivery_time_min  100000 non-null  float64
 11  delivery_delay_min        100000 non-null  float64
 12  fuel_consumption          100000 non-null  float64
 13  fuel_cost                 100000 non-null  float64
 14  driver_cost               100000 non-null  float64
 15  operating_cost            100000 non-null  float64
 16  cost_per_order            100000 non-null  float64
dtypes: datetime64[us](1), float64(8), int64(1), str(7)
memory usage: 16.6 MB

In [175]:
orders.isnull().sum()

order_id                    0
customer_id                 0
vehicle_id                  0
driver_id                   0
route_id                    0
order_date                  0
time_slot                   0
package_type                0
package_weight_kg           0
expected_travel_time_min    0
actual_delivery_time_min    0
delivery_delay_min          0
fuel_consumption            0
fuel_cost                   0
driver_cost                 0
operating_cost              0
cost_per_order              0
dtype: int64

In [176]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [177]:
orders.groupby("package_type")["package_weight_kg"].agg(["min", "max"])

              min  max
package_type
Fragile         1   20
Large          31  100
Medium         11   30
Small           1   10

In [178]:
vehicle_capacity_map = vehicles.set_index("vehicle_id")["max_load_kg"]

assigned_capacity = vehicle_capacity_map[
    orders["vehicle_id"]
].to_numpy()

In [179]:
(orders["package_weight_kg"].to_numpy() > assigned_capacity).sum()

np.int64(0)

In [180]:
driver_license_map = drivers.set_index("driver_id")["license_type"]

assigned_licenses = driver_license_map[
    orders["driver_id"]
].to_numpy()

In [181]:
vehicle_type_for_orders = vehicle_type_map[
    orders["vehicle_id"]
].to_numpy()

required_licenses = pd.Series(
    vehicle_type_for_orders
).map(vehicle_license_map).to_numpy()

In [182]:
(required_licenses != assigned_licenses).sum()

np.int64(0)

In [183]:
(orders["cost_per_order"] < 0).sum()

np.int64(0)

In [184]:
(orders["fuel_consumption"] < 0).sum()

np.int64(0)

In [185]:
orders[["package_weight_kg", "fuel_consumption", "cost_per_order"]].corr()

                   package_weight_kg  fuel_consumption  cost_per_order
package_weight_kg           1.000000          0.033112        0.002677
fuel_consumption            0.033112          1.000000        0.892180
cost_per_order              0.002677          0.892180        1.000000

In [186]:
orders["delivery_delay_min"].describe()

count    100000.000000
mean          7.800919
std          11.338418
min         -16.000000
25%           0.000000
50%           4.700000
75%          14.200000
max          48.200000
Name: delivery_delay_min, dtype: float64

In [187]:
orders["cost_per_order"].describe()

count    100000.000000
mean        367.665004
std         236.119769
min          13.374281
25%         181.924886
50%         338.856763
75%         523.463848
max        1388.089023
Name: cost_per_order, dtype: float64

In [188]:
orders.to_csv(
    "../data/raw/orders.csv",
    index=False
)